New approach, works better

diff --git a/check_influxdb_data b/check_influxdb_data
--- a/check_influxdb_data
+++ b/check_influxdb_data
@@ -33,33 +33,23 @@ pw=$5
 measurement=$6
 warning=$7
 critical=$8
+now=$(date +%s)
 
-result=$(influx -host "$host" -port "$port" -database "$db" -username "$user" -password "$pw" -execute "select COUNT(*) from $measurement where  time > now() - ${warning}s")
+result=$(influx -host "$host" -port "$port" -database "$db" -username "$user" -password "$pw" -precision s -execute "select LAST(value) from $measurement")
 result_value=$?
 if [ $result_value -ne 0 ]; then
     echo "ERROR: could not connect to influxdb, error was: $result."
     exit $STATE_CRITICAL
 fi
-count=$(echo $result | grep -E "^[0-9]+\s[0-9]+$" | grep -o -E "\s[0-9]+$" | sed "s/^\s//g")
-if [ $count -gt 0 ]; then
-    echo "OK: measurement $measurement in $db on ${host}:${port} has received $count values in the last $warning seconds."
-    exit $STATE_OK
-elif [ $count -eq 0 ]; then
-    result2=$(influx -host "$host" -port "$port" -database "$db" -username "$user" -password "$pw" -execute "select COUNT(*) from \"$measurement\" where  time > now() - ${critical}s")
-    result_value2=$?
-    if [ $result_value2 -ne 0 ]; then
-        echo "ERROR: could not connect to influxdb, error was: $result2."
-        exit $STATE_CRITICAL
-    fi
-    count2=$(echo $result2 | grep -E "^[0-9]+\s[0-9]+$" | grep -o -E "\s[0-9]+$" | sed "s/^\s//g")
-    if [ $count2 -gt 0 ]; then
-        echo "WARNING: measurement $measurement has received $count values in the last $warning seconds and $count2 values in the last $critical seconds."
-        exit $STATE_WARNING
-    else
-        echo "ERROR: measurement $measurement has received $count values $count2 values in the last $critical seconds."
-        exit $STATE_CRITICAL
-    fi
+time=$(echo $result | grep -o -E "[0-9]+\s[0-9\.]+$" | grep -o -E "^[0-9]+\s" | sed "s/\s$//g")
+diff=$(( $now-$time ))
+if [ $diff -gt $critical ]; then
+    echo "ERROR: measurement $measurement has received no values in the last $critical seconds."
+    exit $STATE_CRITICAL
+elif [ $diff -gt $warning ]; then
+    echo "WARNING: measurement $measurement has received no values in the last $warning seconds."
+    exit $STATE_WARNING
 fi
 
-echo "UNKNOWN: an unknown error occured."
-exit $STATE_UNKNOWN
+echo "OK: measurement $measurement in $db on ${host}:${port} has received values in the last $warning seconds."
+exit $STATE_OK
